#!/bin/sh
uci -q get uhttpd.openrkn && exit 0
uci set uhttpd.openrkn=uhttpd
uci set uhttpd.openrkn.listen_http='0.0.0.0:7788'
uci set uhttpd.openrkn.home='/www'
uci set uhttpd.openrkn.cgi_prefix='/cgi-bin'
uci commit uhttpd
/etc/init.d/uhttpd restart 2>/dev/null || true
exit 0
